[template]
number_of_shards = 1
codec = "best_compression"


[dashboards]
enabled = true
include = [
  "Winlogbeat-overview.json"
]

[kibana]
enabled = true
host = "https://127.0.0.1:5601"

[elasticsearch]
enabled = true

[[elasticsearch.members]]
host = "localhost"
port = 9200