
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
  - name: Security
  - name: System

#==================== Elasticsearch template setting ==========================
{{~#if cfg.template}}
setup.template.settings:
  {{~#if cfg.template.number_of_shards}}
  index.number_of_shards: {{cfg.template.number_of_shards}}
  {{~/if}}
  {{~#if cfg.template.codec}}
  index.codec: {{cfg.template.codec}}
  {{~/if}}
{{~/if}}
#============================== Dashboards =====================================
{{~#if cfg.dashboards.enabled}}
setup.dashboards.enabled: {{cfg.dashboards.enabled}}
setup.dashboards.directory: {{pkg.path}}/kibana
{{/if}}

{{~#if bind.kibana }}
setup.kibana:
  host: "{{bind.kibana.first.sys.ip}}:{{bind.kibana.first.cfg.port}}"
{{else }}
  {{~#if cfg.kibana.enabled}}
setup.kibana:
  host: "{{cfg.kibana.host}}"
  {{/if~}}
{{/if}}

{{~#if bind.elasticsearch}}
output.elasticsearch:
  hosts: [{{#each bind.elasticsearch.members ~}} "{{sys.ip}}"{{~#unless @last}},{{/unless}} {{/each ~}}]
{{else}}
  {{~#if cfg.elasticsearch.enabled}}
output.elasticsearch:
  hosts: [{{~#each cfg.elasticsearch.members as |member|}} "{{member.host}}:{{member.port}}"{{~#unless @last}},{{/unless}} {{~/each}}]
  {{~/if}}
{{~/if}}

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~